version: '3'

services:
  nginx:
    image: nginx
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 9012:9012
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/:/etc/nginx/logs/:rw